version: '3'
services:

  app:
    build: .
    ports:
      - "3002:3030"
    
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Increased from 1.0
          memory: '2G' # Increased from 1G
    restart: unless-stopped

volumes:
  db_data: